//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CART
    {
        public System.Guid KEY_CART { get; set; }
        public string NAME_CART { get; set; }
        public string ADDRESS_CART { get; set; }
        public string PHONE_CART { get; set; }
        public string CONTENT_CART { get; set; }
        public Nullable<int> STATUS_CART { get; set; }
        public string KEY_USER { get; set; }
        public string CODE_PROMOTION { get; set; }
    }
}
