//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT
    {
        public System.Guid KEY_CONTACT { get; set; }
        public string MODULE_CONTACT { get; set; }
        public Nullable<int> GROUP_CONTACT { get; set; }
        public string NAME_CONTACT { get; set; }
        public string TITLE_CONTACT { get; set; }
        public string EMAIL_CONTACT { get; set; }
        public string PHONE_CONTACT { get; set; }
        public string CONTENT_CONTACT { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public Nullable<int> STATUS_CONTACT { get; set; }
    }
}
