//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAILS_CART
    {
        public System.Guid KEY_CART { get; set; }
        public System.Guid KEY_DETAIL { get; set; }
        public Nullable<int> KEY_PRODUCT { get; set; }
        public Nullable<decimal> PRICE_PRODUCT { get; set; }
        public Nullable<int> QUANTITY_PRODUCT { get; set; }
        public string NOTE_DETAIL { get; set; }
        public Nullable<int> SORT_INDEX { get; set; }
    }
}
