//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GROUP
    {
        public int KEY_GROUP { get; set; }
        public string NAME_GROUP { get; set; }
        public string DESCRIPTION_GROUP { get; set; }
        public Nullable<bool> ENABLE_GROUP { get; set; }
        public Nullable<int> SORT_INDEX { get; set; }
        public string MODULE { get; set; }
    }
}
