//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGE
    {
        public System.Guid KEY_IMAGE { get; set; }
        public string MODULE { get; set; }
        public Nullable<int> KEY_RELATED { get; set; }
        public string RELATED_TYPE { get; set; }
        public string NAME_IMAGE { get; set; }
        public string DESCRIPTION_IMAGE { get; set; }
        public string URL_IMAGE { get; set; }
        public Nullable<bool> VISIBLE_IMAGE { get; set; }
        public Nullable<int> SORT_INDEX { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public string SOURCE_IMAGE { get; set; }
    }
}
