//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int KEY_PRODUCT { get; set; }
        public Nullable<int> GROUP_PRODUCT { get; set; }
        public string MODULE_PRODUCT { get; set; }
        public string NAME_PRODUCT { get; set; }
        public string DESCRIPTION_PRODUCT { get; set; }
        public string CONTENT_PRODUCT { get; set; }
        public string IMAGE_PRODUCT { get; set; }
        public Nullable<decimal> PRICE_PRODUCT { get; set; }
        public Nullable<decimal> SALES_PRODUCT { get; set; }
        public Nullable<decimal> MONEY_SALE_PRODUCT { get; set; }
        public Nullable<bool> PINED_PRODUCT { get; set; }
        public Nullable<int> SALE_DAY_COUNT { get; set; }
        public Nullable<int> SALE_MONTH_COUNT { get; set; }
        public Nullable<System.DateTime> SALE_DAY_UPDATED { get; set; }
        public Nullable<System.DateTime> SALE_MONTH_UPDATED { get; set; }
        public Nullable<int> RATE_POINT { get; set; }
        public Nullable<int> RATE_COUNT { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public Nullable<System.DateTime> DATE_UPDATED { get; set; }
        public Nullable<bool> ENABLE_PRODUCT { get; set; }
        public string META_TITLE { get; set; }
        public string META_KEYWORDS { get; set; }
        public string META_DESCRIPTION { get; set; }
    }
}
