//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAddress
    {
        public string IdUser { get; set; }
        public System.Guid KeyAddress { get; set; }
        public string NameAddress { get; set; }
        public string DetailAddress { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string PhoneAddress { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    }
}
