//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_RULES
    {
        public string KEY_USER { get; set; }
        public System.Guid KEY_RULE { get; set; }
        public Nullable<bool> ENABLE { get; set; }
    }
}
